dist: xenial
language: minimal

cache:
  directories:
    - $HOME/.cache/git-remote-hg

script:
  - ./tools/check-versions hg:$HG_VERSION

matrix:
  include:
    - env:
    - env: HG_VERSION=@
    - env: HG_VERSION=5.0
    - env: HG_VERSION=4.9
    - env: HG_VERSION=4.8
    - env: HG_VERSION=4.7
    - env: HG_VERSION=4.6
    - env: HG_VERSION=4.5
