name: mirror

on:
    workflow_dispatch:
#    schedule:
#        - cron: "30 11 * * *"  # Run at 3:03am daily

jobs:
    mirror-hgmo:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout main
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
              with:
                  persist-credentials: false
                  path: "."

            - name: Cinnabar cache
              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
              id: cache-cinnabar
              with:
                  path: |
                    bin/git-cinnabar
                    bin/git-remote-hg
                  key: ${{ runner.os }}-${{ hashFiles('cinnabar-rev') }}

            - if: ${{ steps.cache-cinnabar.outputs.cache-hit != 'true' }}
              uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659  # v1.17.0
              with:
                  cache: false

            - if: ${{ steps.cache-cinnabar.outputs.cache-hit != 'true' }}
              name: Build git-cinnabar
              run: |
                  sudo apt-get update && sudo apt-get install libcurl4-openssl-dev ca-certificates
                  cargo install --git https://github.com/glandium/git-cinnabar --rev $(cat cinnabar-rev) --root . --no-track
                  ln -s git-cinnabar bin/git-remote-hg

            - run: echo "`pwd`/bin" >> $GITHUB_PATH

            - name: mirror https://hg.mozilla.org/comm-unified
              uses: ./.github/actions/mirror-hgmo
              with:
                  source-hg-repo-url: 'https://hg.mozilla.org/comm-unified'
                  source-hg-bookmarks: 'comm comm-beta comm-release comm-esr115 comm-esr128 comm-esr140'
