name: mirror

on:
    workflow_dispatch:
    schedule:
        - cron: "30 11 * * *"  # Run at 3:03am daily

jobs:
    mirror-hgmo:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout main
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
              with:
                  persist-credentials: false
                  path: "."

            - name: Cinnabar cache
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
              id: cache-cinnabar
              with:
                  path: |
                    bin/git-cinnabar
                    bin/git-remote-hg
                  key: ${{ runner.os }}-${{ hashFiles('cinnabar-rev') }}

            - if: ${{ steps.cache-cinnabar.outputs.cache-hit != 'true' }}
              uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7  # v1.16.0
              with:
                  cache: false

            - if: ${{ steps.cache-cinnabar.outputs.cache-hit != 'true' }}
              name: Build git-cinnabar
              run: |
                  sudo apt-get update && sudo apt-get install libcurl4-openssl-dev ca-certificates
                  cargo install --git https://github.com/glandium/git-cinnabar --rev $(cat cinnabar-rev) --root . --no-track
                  ln -s git-cinnabar bin/git-remote-hg

            - run: echo "`pwd`/bin" >> $GITHUB_PATH

            - name: mirror https://hg.mozilla.org/comm-unified
              uses: ./.github/actions/mirror-hgmo
              with:
                  source-hg-repo-url: 'https://hg.mozilla.org/comm-unified'
                  source-hg-bookmarks: 'comm comm-beta comm-release comm-esr115 comm-esr128 comm-esr140'
